# Generated by Django 2.2.1 on 2019-05-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0009_auto_20190504_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_caption', models.CharField(max_length=500)),
                ('photo_picture', models.FileField(default='', upload_to='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuistcis.Activity')),
            ],
        ),
    ]
