# Generated by Django 2.2.1 on 2019-05-11 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0010_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('news_content', models.CharField(max_length=5000)),
                ('news_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuistcis.News')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
