# Generated by Django 2.2.1 on 2019-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0012_auto_20190511_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(max_length=10000),
        ),
    ]
