# Generated by Django 2.2.1 on 2019-05-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0013_auto_20190511_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
    ]
