# Generated by Django 2.2.1 on 2019-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0016_auto_20190522_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=500)),
                ('note_content', models.TextField(max_length=10000)),
                ('note_date', models.DateField()),
                ('new_author', models.CharField(max_length=100)),
            ],
        ),
    ]
