# Generated by Django 2.2.1 on 2019-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0018_auto_20190524_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_mainphoto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
