# Generated by Django 2.2.1 on 2019-05-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0019_news_news_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=500)),
                ('program_description', models.TextField(max_length=10000)),
                ('program_mainphoto', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=500)),
                ('program_description', models.TextField(max_length=10000)),
                ('program_intake', models.CharField(max_length=50)),
                ('program_duration', models.IntegerField(max_length=10)),
                ('program_tuition', models.IntegerField(max_length=10)),
                ('program_mainphoto', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('schools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuistcis.Schools')),
            ],
        ),
    ]
