# Generated by Django 2.2.1 on 2019-05-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0020_programs_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programs_type_name', models.CharField(max_length=500)),
                ('Programs_type_description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='programs',
            name='Programs_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nuistcis.Programstype'),
            preserve_default=False,
        ),
    ]
