# Generated by Django 2.2.1 on 2019-05-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0021_auto_20190525_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programstype',
            old_name='Programs_type_description',
            new_name='programs_type_description',
        ),
        migrations.RenameField(
            model_name='programstype',
            old_name='Programs_type_name',
            new_name='programs_type_name',
        ),
    ]
