# Generated by Django 2.2.1 on 2019-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0023_auto_20190525_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programs',
            name='program_tuition',
            field=models.IntegerField(),
        ),
    ]
