# Generated by Django 2.2.1 on 2019-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0024_auto_20190525_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='program_language',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
    ]
