# Generated by Django 2.2.1 on 2019-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0025_programs_program_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=500)),
                ('article_content', models.TextField(max_length=10000)),
                ('article_date', models.DateField()),
                ('articles_author', models.CharField(max_length=100)),
            ],
        ),
    ]
