# Generated by Django 2.2.1 on 2019-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0026_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websitelogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('website_logo', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
        ),
    ]
