# Generated by Django 2.2.1 on 2019-06-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0027_websitelogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='program_description',
            new_name='school_description',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='program_mainphoto',
            new_name='school_mainphoto',
        ),
    ]
