# Generated by Django 2.2.1 on 2019-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0028_auto_20190611_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excellentscholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_name', models.CharField(max_length=500)),
                ('scholar_job', models.TextField(max_length=500)),
                ('scholar_facebook', models.TextField(max_length=500)),
                ('scholar_wechat', models.TextField(max_length=500)),
                ('scholar_linkedin', models.TextField(max_length=500)),
                ('scholar_photo', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
            ],
        ),
    ]
