# Generated by Django 2.2.1 on 2019-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0030_auto_20190625_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excellentscholar',
            name='scholar_description',
            field=models.TextField(max_length=500),
        ),
    ]
