# Generated by Django 2.2.1 on 2019-06-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuistcis', '0031_auto_20190625_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excellentscholar',
            name='scholar_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='excellentscholar',
            name='scholar_facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='excellentscholar',
            name='scholar_job',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='excellentscholar',
            name='scholar_linkedin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='excellentscholar',
            name='scholar_wechat',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
